apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[{"apiVersion":"charts.helm.k8s.io/v1alpha1","kind":"Cockroachdb","metadata":{"name":"example"},"spec":{"CacheSize":"25%","ClusterDomain":"cluster.local","Component":"cockroachdb","ExternalGrpcName":"grpc","ExternalGrpcPort":26257,"ExternalHttpPort":8080,"HttpName":"http","Image":"cockroachdb/cockroach","ImagePullPolicy":"Always","ImageTag":"v2.1.3","InternalGrpcName":"grpc","InternalGrpcPort":26257,"InternalHttpPort":8080,"JoinExisting":[],"Locality":"","MaxSQLMemory":"25%","MaxUnavailable":1,"Name":"cockroachdb","NetworkPolicy":{"AllowExternal":true,"Enabled":false},"NodeSelector":{},"PodManagementPolicy":"Parallel","Replicas":3,"Resources":{},"Secure":{"Enabled":false,"RequestCertsImage":"cockroachdb/cockroach-k8s-request-cert","RequestCertsImageTag":"0.4","ServiceAccount":{"Create":true,"Name":null}},"Service":{"annotations":{},"type":"ClusterIP"},"Storage":"100Gi","StorageClass":null,"Tolerations":{},"UpdateStrategy":{"type":"RollingUpdate"}}}]'
    categories: Helm
    description: CockroachDB
    containerImage: quay.io/helmoperators/cockroachdb:2.0.9
    createdAt: 2019-01-23T12-10-51Z
    support: a-robinson
  name: cockroachdb.v2.0.9
  namespace: default
spec:
  customresourcedefinitions:
    owned:
    - description: CockroachDB
      displayName: cockroachdb
      kind: Cockroachdb
      name: cockroachdbs.charts.helm.k8s.io
      version: v1alpha1
  keywords:
  - helm
  displayName: cockroachdb
  provider:
    name: Helm Community
  maturity: stable
  version: 2.0.9
  links:
  - name: Helm Chart Source
    url: https://github.com/cockroachdb/cockroach
  installModes:
  - type: OwnNamespace
    supported: true
  - type: SingleNamespace
    supported: true
  - type: MultiNamespace
    supported: false
  - type: AllNamespaces
    supported: true
  maintainers:
  - email: alex@cockroachlabs.com
    name: a-robinson
  selector:
    matchLabels:
      alm-owner-etcd: couchbaseoperator
      operated-by: couchbaseoperator
  labels:
    alm-owner-etcd: couchbaseoperator
    operated-by: couchbaseoperator
  install:
    spec:
      deployments:
      - name: cockroachdb-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: cockroachdb
          template:
            metadata:
              labels:
                name: cockroachdb
            spec:
              serviceAccountName: cockroachdb
              containers:
              - name: cockroachdb
                image: REPLACE_IMAGE
                ports:
                - containerPort: 60000
                  name: metrics
                imagePullPolicy: Always
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: OPERATOR_NAME
                  value: cockroachdb
              container:
              - image: quay.io/helmoperators/cockroachdb:2.0.9
      clusterPermissions:
      - rules:
        - verbs:
          - use
          apiGroups:
          - security.openshift.io
          resources:
          - securitycontextconstraints
          resourceNames:
          - privileged
        serviceAccountName: cockroachdb-operator
      permissions:
      - rules:
        - apiGroups:
          - couchbase.com
          resources:
          - couchbaseclusters
          verbs:
          - '*'
        - apiGroups:
          - storage.k8s.io
          resources:
          - storageclasses
          verbs:
          - get
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - '*'
        serviceAccountName: cockroachdb-operator
    strategy: deployment
  description: |
    CockroachDB is a scalable, survivable, strongly-consistent SQL database.
    
    _This was generated from a Helm chart automatically._
    
    Many HElm charts require running a root, your admin will need to allow this with a SecurityContextConstraint.
  icon:
    mediatype: image/png
    base64data: iVBORw0KGgoAAAANSUhEUgAAAXsAAAA8CAYAAACHFBprAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAEkFJREFUeNrsXU1sG8cVHqluEtexTSeKgdQBRKV1UANBQiVok0sjCnCBFD1I8q0nkZfmKBHoLQdRh94KUDq2F1FAD+3Fkg9BWyCAVsnJLVLRaQoHbVqvitpBE8dh4jbOj9N0Hv1WGo5md97uzi5J8X3AQj9c7pudn2/ee/PmzYjQ8Mh3fliUP0p4PS2vAn5UVm5ry6uFv/vy2pWXB/97/+3ftoVjyDKVUf5JLJfAnwXlNk8p2xUsH5THFwwGgzHkGEEynZU/puQFP4spn9lC4l2XRNtKSO4lLMuMQu5J4WN5LsnybHKTMxiMoSR7Saw7Dgg1imhX5dW0afyyHAUk+IUMy9OW5TjFzc5gMIYNo6DxxrjfE/vuGwrASmjI65ok8zoS+gGSh8/gHnmtxST6wIqggjV7BoMxtJo9EPCO2Hff+EiK4Pf2pSbsWbRx1b9fFtFuINDuV+Uz6/j9RfljSXT73k3fgTJsI7n7UX549O8XlfKUlOdMZLGmwGAwGH1P9gpBAilupl3QRH/7vIj2//tIvqUIgm+KFH5/pTxFJP02++wZDMZQk31WwIXfBdEdyRMFmASWJSk3uWkYDAZjQMheIX0g+0aEJs8kz2AwGBliNCc5NlcMuG3YxcJgMBiDqtnjIu6WsEfZAOFPp/XRMxgMBiNnzT6C6D1xbwFWBdy7YQrPZDAYDEYfkz2Qt4HoYYMVaPBV+fuK9lkRJgcmfAaDwRgQspeEDRukygairwZ/yN9r8kdVuwcmhzVuGgaDwXCHTHz2GHK5EUX02v0QqbOo/Xs52HzFGGzgXoci5d6oTXyMQ9k39ISGYWjzel6fkT0O7B2tASH75CTBEqho/54clAbG8FJhsGY8pQ7aQzqgTZN5GNmP8LAcqr6xJWj7cDxw/3KNJceRDJ65phF9J8qG8D1w6QSpF9RnTfYxuc+I7pQMJiwp3wlSP0A+os0hIv8SDzVGCIpcBfnAqc8e3Tf6LD1HITW854D/HvPn9BPJV+QFSdu2UFuNQ2RBZk+YxD4Ea0axCHhAM5jsGQOj2Te0v4HAy+ja8UWIKwMJL0iq1tYsgyX5ebPXWjD6FuNm5bShApd8dvWQ7x7mAc0IG1OMQSN70HgNg7qgujHwvriPLqAGXe+lNi+yjRA67GQ4gRbNvGCXDmPfmm/JsRX0jQVWCrKFs8UwdG1k1Vg9S0+cA9EDhibyyHZYDi/QDrWmH8UhvEDbD5q9kkM+KwS+7mafE30Lr138exzrhRpeNgzg8wQYYfBZu+9zskfzPGss5En2io+eQl5w9OJKlOURsveAwWAwckHqaBxMbVDJoawlXOjNCw2iJg/upbrNxYQHp7BWy2AwBpPsBf1gEheYzUmrrxDeq7NRLOY6Au8AZDAYPYELN86M+seFly+LVxrPiM8++Xp60v1BS3yw/aT43+d7xZwSB5OnZQGbW4q6UcxE9s4mx5AY/Ux36vZCZi+hv2/SdA7Kec3CxfPiyslCliITLG7d6s4lvYHhfTmtQoZkvzcYxsY/FmfO3RLnX/pzh/DT4OGpt8TR8ffE/Y/eEnd2T+em2aOv3kbItYTktpuybLNif9duMeI+X+BO3bTn7io7hWctMts4mQW7g/0Mra7QyViP2MD2tLnkWpiUTyUvCBmuGOQHhHKKQEJqexVC7oMfUFfQTonOXMY6iZSjyfJQVpqJS5UZJa+F8rZdnQGN7RPIL4XIbYp7UW7O+uGzP/9a1Gl7JsXuI/zZeuOnX/oxZVVEvLVQH/ml05ekvLZTssdG3yOAxyTRAx5/9t/iuQvviMsXv53ouceeuCGOnb3R+f2BRz9Uyb4zeDOeuW0TSjvFBqikg2sWCatI/EowGCpI/NW4AxtJfimGJVLAe+FqyO97OCk6a6uEYbBFwjvA5zVFRkNER08VLOVcxLorxCgjfGcxTr1hG62JeBEsat8AWXNUxQXHO5RzIca7BSlQFlEhWE0TZiyfURfa3p0QwDvOyvtdHohUijEeyhp5B4pQk0j8RZHcC7Am5XUmO1XWqIOX38MZJHvA9y78retvsqlx/I449fzbe3/f9/DtSJkZYMryeVKi72wigTjy4EJX0HTUMzFB3IZIHpIG39vCZGTUAQX3bol0LqeyS0ssxX6HEpXIFBmFhGUs4D6ChkgealvG9qoQ6mNLpAtVLOMzqBbvTsxJzDRJLiX9LtbtUkx5/XI+RgnLfk0ScV1eWZcJ+seOlFPKhOxPjN3p+vD8S2+K+7/xRTz3zQt/EaP33d37G9w4BvLKEjaC23YlCLRtvPwIoq84ErdIIXyU2Xf5iETyjW3jMQZHI0UZqcdvUklqLYzw0Y3RcEVCtvxTSPRborcx8KWEdZtXtGAcAOlvqUScEQoop+CC7LtmJ/DZ6+RfepHupgb3jYHckw7eJAOW0pm9PHoDmquuO+liVOK1jGSmrQfKfocWWkfLhs+uiHt+TMoATKNtbWRgdTZC+iTVjUJ1XywQJrFB3hQ404dlKuVI+J0xnXaB9qTthqdf9MXV18+Ij98/GnkfaPMnn/m78TPw23/67qk8NHvrs/OIOlEWCG1oIpm1sPPMECwTIM6JhDLbKPOSwTwtZFAPJYubwXpIvfwMordWcJKLWmArpChnhVDvUNZNtAx9vH/e0ucCt0c1hvUJcubUNRp8942IdyxC+4dYmBS3FshaVybVAr5bLqHSDqz1tPASyuxYcJLwp00LqhFjft0gayaib3eiGNOS/d7DTzxyx3gDuHHAf//qL56yaPXXxZEH7/S7hpBXSBeFdHWS85DU6pbvw8CeNURGJJHZkSufN+7a9aMQfRTRkBffgPzkMy8RtG8fLYTNGG6ZJUK/mdPIFNqrTnDVwUKqHlUSVaZlfTEe371msZCKugWEk4SNsI15neR3WxmRPTwXdqx33J9oeTR6aZFKojaGYaPWPmuxxEoiXqLHXSnPM0w2sA4Q1pecuHH2cHwsnKgff/Y9q+/++JP/HARzMA+tnuJjDI3WwIFnczXNGLR6m8y5CGLddVwHFKKvZhCVBVoTbJQLUmp7xLLaLMJqRAhgjeBmmjWU08PLJyokNhmmuraF/nlhkTUZhd7O4UbGZvB8bKea6MPd6ZKUIeSyjpZ0VNjpgqMF2/VI70keLw1Ef+6F66GfQzz9AGj1/WJy+oTQz9WY5DFLGNReHhZPDKJvZlD365qbjjKJ2QixaXEztS1EcGByhrOcYT8BXhNKdNdkWFsQQm9LhH5imqjiujcSIyxOH+uwbzdSgYtGXnMiPOou60XkzsToLJ/97ZvRPvlz378uWr8zK0APPnGDKX4fttDPTcqgsJwbUNB8tDaZlwguEnB9jGtabhLtzuYj9nM86KVpIJGi9o6lNHWn3LMYk4hN7eBy0i0T2sEmb1XsrydlDae70zNCTYRviEyVHQAtg0aUxp+W7LeDCrYtwEKkDvj1TfeBZn9ItG4XKBHqnNr5o55VVMi4RHiWjWjqOb0/rDlU8iB8oiun7KDuPNvk3IO+7qJPbFKUE0f4qN/JAzR8ScqrIaRM5ZYpiNPX/ncSLQNTP2kGPv4jeb4s7KzVtXsK0SuROEm1xcOEtuP7hLD4nLPKqZICSyLnsw1STBhO+mtEtIyujQdEXVCIIGl8ehSusBGeCF7KCb0cY2IAot+L5EpL9l2d7+buiQOx9ipgR61O9hBWGRO7GTYEaYt6xuRX5vFgn5zy0u776Z3FwWiZwNfLxz0OCGDRVmrmeYiqSVldbqG0C7Rdne/jm3ZXjg5DOoQufPbuQ5EyMzDbbRoxD6r+QKNPtsH3BLjr9ZqI3jvAGOLxIScVSM1QdkX2XZrw9asPRd58whCeadsx+/kHx2Nr3xlr9/MpB2nZcBX7nFjyJlVog0mCm2FxWEautkmqLtLl32H0CJJ88xzrIGsLM2imI3s95OlfFrIHxE2Opvnr88hVbVsATXxilrL1XL8qym1eH/bRPDVHsNyCzVJNy70Lw6bdK9lIqZOmh1fTcVGmBKMXYwnaclm7mhbeAC2/6GKB1gteAHz2cGgJNfkZxV+vuXHyIMJNwmACrWquR6RZItZDOYYF44voRdqSyG8SUlPuLovo+OMgnUCth4O3LaJzyFvXeHBvgW0CpFqW0K7GDWe2TJqG9+oXBeAwYT6CR0nKKG7UCrMaTDmaoH8uuNhU1aUJ/+ON05E3h6VVMAHy2CunVFG0bhfmcksQdjRijvksyN72jlaNikIe2uahTF1XCeo/+N0naKSLPXaDtRy0eZyJ2Xavq/zttmcUEo6BoQX6z2cT1rcVmLs+TAktjzoYnF0HaV997bFosh+jk/0nu6dNWnceWCbcs0YgVR3jDgZZmeC6sG5zjznBlHo4sCltsdTDMbydsi0AtqyM6sasqInNc5WoD62Rdh/X+6ARfQm17jCsupATcTBKyVW6hD0ShkVaW1QOBaDR//ev39Q7sp9Hw2BIn00WEO4OLpZRUSbI3rQMssgDIHACspnr6wkmUdLkBlq2y4mBqN1Xeqjd2+quFOU+wboqp5Rh7V8J24TybqRzBqAOhjF6Cna24iaoqBQgzbjHFlqsByNcbapaVwnmDxfPivM/eTPVA2+/NW4jqKxRFbRTfJZkJ54XSvpaMKOVQ5iDA5FnBN3PuWkhbHBdwI7BFVWTU46pixpULUNWRMge2BR2//gO3reOz2kr71lW3hH+7zlMB23z3Qt87+m8BzO2tWchbJgoC5huWSdgG1k249QjkC/kztH6xIJIloFynVDvFZSxrCpk+D/oF1Mou4DXijhkMBBsMOafFpZzgVGxqzkqR1R/ao24emE8MmyPzOZXPKPL5uLPntsL0YQF2tM/+qNRq7/x6xdUfz0Q6ETejYgnO+UR3teVJhYJdEfYQ+vUaKgCcTKZNi0YosxrLidLddMTWgUFYT8ztYpWVUubyCindi2ji6plmAQDt0PZMsmuK5aVT7Em8fkUxcBXLMaisGfLhHJMqmWQsq4Rvxeky6Bq0x7Wn6/J2xDuUhUbx7GSOdSmqIA/uh3Sf+sWt1IN66SVVAmRZJr2qE4TJmGjlUFW2Pv4IV4HW7lWXGa97PI5gXZvw93/PBCq1WsLs3lr9YHWVhM92JaPg40y26uHfFOIfiUsMgRlVh2+xoIyEL/CyYtytN0a3veh/N6WRuRWK0v5bl0hgSDE1TYggNQ2lPuvYdlt7eUR+0lRaS+K26lmmGy8GP0ijtukrLxz3TD5ukBRPykN23hHRB+uEqDTNpQ2MaCh9I2y6D06h8yYiD5GH1Ivm6zVUYcE1VS0THH1tTPGTVZqdsy7t48aJoCj4qM/fUsvaM9MPzSJl3sgt+l4omni5JWXzJLLQUX03Yse9xOXAQRhaZzTKD6tBO/VDjRq10rAEAPaAU6nyivgpAprAq7z2XeRyau/fKoTd69Cz3qp75C9tf2kSbtp93ggg6YzKbKJNQ8lWCSQasqB1sY6rBLf1YVMIbJJa7HczyNY1t2cA8UkOFawGWFFJJEB35lO+F5AThOO+n9bDC98JN7JBBp90kllMphURh13dk/VboDYX//Vub3PTZr+F7f2yR40em3HrNcvya6gw8NhEThgmik7rYcT4wQeROFbtO3JBDKD82In9YVBolUxgQQR9z03USudcJ0wrt+1eyxjDfvIZgIiWMY+sUmQsRyjr8E6TY2Y+ylUw8f+X01gIfjYlyaoSsch0+JXkHQn5JV1/w3GyJw+qWSR4hgaE8z3QuDOOXPug87hJe/vnjhwM2j2x87e20BlcN/U+nAweziAquimCBbBpiIqf1fsLzomMaV9rNcqRnAEK/0FA8FfEfaTpajmO9R/Dd+zbJHZEuFx3kmjZNoh1uM6sdMHlpPXiz6CoYZBH5kKKWPQXq2YMuoYGTWLzy4YnrtpUCSmhd03blM+mrigH/QJ03rRNrHP14SbHD9x2jmpVh2nrK0Yh4infZ/OWLFZCyNZdHYkpK4NBBdeviwuXzx7QLs/cvyOGDvfEu+98l19UbYWVyNlMBgMRo5kj4TfFbYI+XJ0/32A0fvu6kTfHEJzj8FgMDJDZln0P7n5zu+PjZ0tBibel1+Ei/rqy1HdxPqx/P6n3DwMBoPhBqMZPz/YyEBFJySp19E3DAaDcdgwkrUAJYc75QBjJnoGg8EYQM0+iOqwhaIx0TMYDEaGyOXkW/C/y+s3x8bOgpb/vPZxU14/ZqJnMBiM7DCSt0Al0x8QP4dXMhgMRg74vwADAMVKxxvK+JWTAAAAAElFTkSuQmCC
